### ISSUE TITLE
 Three javascript tests are failing.

### ISSUE THREAD

**Issue by zubrabubra** [devicehive/devicehive-java-server#177]
TypeError: Converting circular structure to JSON
-----
    at Object.stringify (native)
    at integration-tests/rest-oauth-client.js:135:32
    at integration-tests/common/request.js:94:24
    at integration-tests/common/utils.js:249:28

AssertionError: Expected value for 'message' should be: 'You can not delete current user or owner of current access key'
-----
    at integration-tests/common/utils.js:470:20
    at Array.forEach (native)
    at Object.utils.matches (integration-tests/common/utils.js:451:14)
    at integration-tests/common/request.js:91:23
    at integration-tests/common/utils.js:298:28

AssertionError: Expected value for 'message' should be: 'You can not delete current user or owner of current access key'
-----
    at integration-tests/common/utils.js:470:20
    at Array.forEach (native)
    at Object.utils.matches (integration-tests/common/utils.js:451:14)
    at integration-tests/common/request.js:91:23
    at integration-tests/common/utils.js:298:28

**Comment by YermakovSergiy** [comment]
I didn't see this error before : TypeError: Converting circular structure to JSON. For last month there were only the last two.
