### ISSUE TITLE
Need help on backend crashing

### ISSUE THREAD

**Issue by orino76** [devicehive/devicehive-java-server#516]
Hi,

I am running a devicehive server 3.4.5.1 using docker-compose on CentOS 7. and I am getting the following error time to time and have to restart the image. Could you please help to have a look and advice for possible cause and solution? Thank you,

`2018-05-16 03:13:14.063 [pool-2-thread-2] ERROR  c.l.disruptor.FatalExceptionHandler - Exception processing: 28010 com.devicehive.model.ServerEvent@65bec9b7
java.lang.ExceptionInInitializerError: null
        at com.devicehive.model.enums.SortOrder.parse(SortOrder.java:55) ~[devicehive-common-3.4.5.jar!/:3.4.5]
        at com.devicehive.model.rpc.ListDeviceRequest.isSortOrderAsc(ListDeviceRequest.java:124) ~[devicehive-common-3.4.5.jar!/:3.4.5]
        at com.devicehive.messages.handler.dao.list.ListDeviceHandler.handle(ListDeviceHandler.java:51) ~[classes!/:3.4.5]
        at com.devicehive.proxy.ProxyServerEventHandler.handleClientRequest(ProxyServerEventHandler.java:103) ~[devicehive-proxy-ws-kafka-impl-3.4.5.jar!/:3.4.5]
        at com.devicehive.proxy.ProxyServerEventHandler.onEvent(ProxyServerEventHandler.java:75) ~[devicehive-proxy-ws-kafka-impl-3.4.5.jar!/:3.4.5]
        at com.devicehive.proxy.ProxyServerEventHandler.onEvent(ProxyServerEventHandler.java:45) ~[devicehive-proxy-ws-kafka-impl-3.4.5.jar!/:3.4.5]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.3.6.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key NOTIFICATION_NOT_FOUND_LOG
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450) ~[na:1.8.0_151]
        at java.util.ResourceBundle.getString(ResourceBundle.java:407) ~[na:1.8.0_151]
        at com.devicehive.configuration.Messages$BidBundle.get(Messages.java:156) ~[devicehive-common-3.4.5.jar!/:3.4.5]
        at com.devicehive.configuration.Messages.<clinit>(Messages.java:48) ~[devicehive-common-3.4.5.jar!/:3.4.5]
        ... 10 common frames omitted
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key NOTIFICATION_NOT_FOUND_LOG
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at com.devicehive.configuration.Messages$BidBundle.get(Messages.java:156)
        at com.devicehive.configuration.Messages.<clinit>(Messages.java:48)
        ... 10 more
Exception in thread "pool-2-thread-3" java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class com.devicehive.configuration.Messages
        at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:165)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.devicehive.configuration.Messages
        at com.devicehive.model.enums.SortOrder.parse(SortOrder.java:55)
        at com.devicehive.model.rpc.ListDeviceRequest.isSortOrderAsc(ListDeviceRequest.java:124)
        at com.devicehive.messages.handler.dao.list.ListDeviceHandler.handle(ListDeviceHandler.java:51)
        at com.devicehive.proxy.ProxyServerEventHandler.handleClientRequest(ProxyServerEventHandler.java:103)
        at com.devicehive.proxy.ProxyServerEventHandler.onEvent(ProxyServerEventHandler.java:75)
        at com.devicehive.proxy.ProxyServerEventHandler.onEvent(ProxyServerEventHandler.java:45)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143)
        ... 3 more`

**Comment by orino76** [comment]
The problem has been resolved and it is caused by incorrect parameters sent to the backed.
