### ISSUE TITLE
Response message is failed: Plugin not authorized

### ISSUE THREAD

**Issue by mapleting88** [devicehive/devicehive-java-server#537]
I setup my DeviceHive-3.5.0 via manual installation,when I start up the devicehive-backend with the devicehive-backend-3.5.0-boot.jar, it reports a error "Response message is failed: Plugin not authorized"
the whole message is:
2019-03-21 15:53:23.875 [XNIO-1 task-13] WARN   c.d.p.c.WebSocketKafkaProxyClient - Response message is failed: Plugin not authorized
2019-03-21 15:53:23.876 [XNIO-1 task-13] ERROR  io.undertow.websockets.core.request - UT025007: Unhandled exception for annotated endpoint com.devicehive.proxy.client.WebSocketKafkaProxyClient@70d4e44e
com.devicehive.exceptions.HiveException: Response message is failed: Plugin not authorized
	at com.devicehive.proxy.client.WebSocketKafkaProxyClient.lambda$onMessage$0(WebSocketKafkaProxyClient.java:114) ~[devicehive-proxy-ws-kafka-impl-3.5.0.jar!/:3.5.0]
	at java.util.Collections$SingletonList.forEach(Collections.java:4822) ~[na:1.8.0_201]
	at com.devicehive.proxy.client.WebSocketKafkaProxyClient.onMessage(WebSocketKafkaProxyClient.java:109) ~[devicehive-proxy-ws-kafka-impl-3.5.0.jar!/:3.5.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$2.onMessage(AnnotatedEndpoint.java:142) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
	at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:281) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:162) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:159) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:575) 

What can I do to resove it? Is there any service must be started befor?

**Comment by itrambovetskyi** [comment]
Hi @mapleting88,

I think that you bumped into this problem because of the wrong configuration of **devicehive-ws-proxy** service. You should disable Plugin Manager.
Could you please share with me your **devicehive-ws-proxy** configuration?

**Comment by mapleting88** [comment]
[cid:_Foxmail.1@da03ae6f-bd5f-a1ba-d8df-03a0c57fa85d]
this is the pic of the config.json in the directory devicehive-ws-proxy-master/src


________________________________
dingfengfeng@hotmail.com

**Comment by mapleting88** [comment]
i just start up one process using the port 3000,Should i start up an other process with port 3001?


________________________________
dingfengfeng@hotmail.com

**Comment by mapleting88** [comment]
Thx for your help,I have resolved the problem.We must start up to process to listen the inner messages and the outer messages.But I only started up one,So the outer system can not receive the response messages.
Thank you for an other once.
________________________________
dingfengfeng@hotmail.com
